# yaml-language-server: $schema=https://raw.githubusercontent.com/BGforgeNet/bgforge.yml/refs/heads/main/schema.json

translation:
  tra_dir: data/text
  extract_format: sfall
  skip_files:
    - game/pipboy.msg

mls:
  translation:
    directory: data/text/english/dialog
