language: minimal
dist: bionic
sudo: false

cache:
  directories:
    - $HOME/.cache/build

addons:
  apt:
    update: true
    packages:
      - gcc
      - moreutils
      - p7zip
      - wine-stable
      - wine32

before_install:
  - ./extra/prepare.sh

script:
  - ./extra/buildall.sh
  - ./extra/publish.sh

env:
  global:
    - sfall_version: 4.1.9.1
    - mpack_version: 4.1.9.1
    - mod_name: upu
    - extra_dir: extra
    - bin_dir: extra/bin
    - release_dir: release
    - mods_dir: release/mods
    - mpack_7z: mpack.7z
    - WINEARCH: win32
    - WINEDEBUG: -all

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - upu*.zip
    - upu*.dat
  skip_cleanup: true
  on:
    tags: true
    branch: master
