language: minimal
dist: bionic

services: xvfb
addons:
  apt:
    packages:
    - wine-stable
    - wine32
    - xvfb
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
before_install:
  - wget http://files.jrsoftware.org/is/5/innosetup-5.6.1.exe
  - wineboot --update
  - wine innosetup-5.6.1.exe /VERYSILENT /SUPPRESSMSGBOXES

script:
  - echo "script"
before_deploy:
  - echo "before deploy"
