name: build

on: [push]

env:
  sfall_version: 4.3.4
  mpack_version: 4.3.4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: ./extra/tests.sh

      - name: Install packages
        run: |
          set -xeu -o pipefail
          sudo dpkg --add-architecture i386
          sudo apt -qq update
          sudo apt-get install -o=Dpkg::Use-Pty=0 -y crudini dos2unix gcc p7zip wine-stable wine32
          wineboot

      - name: Build and package
        run: ./extra/full.sh

      - name: Upload artifacts - exe
        uses: actions/upload-artifact@v3
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: upu.exe
          path: upu*.exe

      - name: Upload artifacts - translations zip
        uses: actions/upload-artifact@v3
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: upu_translations.zip
          path: upu*_translations.zip

      # so that main glob doesn't catch it
      - name: Remove translations zip
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: rm -f upu*_translations.zip

      - name: Upload artifacts - main zip
        uses: actions/upload-artifact@v3
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          name: upu.zip
          path: upu*.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            upu*.zip
            upu*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
