name: build

on: [push]

env:
  sfall_version: 4.2.8.1
  mpack_version: 4.2.8.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get tag name
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName

      - name: Run tests
        run: ./extra/tests.sh

      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt -qq update
          sudo apt -qq remove parallel
          sudo apt-get install -o=Dpkg::Use-Pty=0 -y crudini dos2unix gcc moreutils p7zip wine-stable wine32
          #sudo apt-get install -qq -o=Dpkg::Use-Pty=0 -y crudini dos2unix gcc moreutils p7zip wine-stable wine32 docker.io >/dev/null 2>&1
          wineboot >/dev/null 2>&1

      - name: Build and package
        run: |
          . extra/env.sh
          ./extra/prepare.sh
          ./extra/buildall.sh
          ./extra/package.sh

      # - name: Upload release artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: release
      #     path: build/int2ssl

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          files: |
              upu*.zip
              upu*.dat
              upu*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
