name: Binary snapshots
on:
  push:
    branches:
      - master
    paths:
      - "**/*.pro"
      - "**/*.map"

permissions:
    contents: write

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: BGforgeNet/BGforge-MLS/actions/binary@actions/binary/v1
