name: Poify/Unpoify
on:
  push:
    paths:
      - "data/text/**" # tra_dir
  pull_request:
    paths:
      - "data/text/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Poify/Unpoify
        uses: BGforgeNet/msg2po@master
        with:
          poify: true
          unpoify: true
          push: true
          single_commit: true
