name: pr

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Fallout tests
        uses: BGforgeNet/fallout-tests@master
        with:
          scripts_h: scripts_src/headers/scripts.h
          scripts_lst: data/scripts/scripts.lst
          scripts_dir: scripts_src
          dialog_dir: data/text/english/dialog
          worldmap_path: data/data/worldmap.txt
