name: ScanMsg

on:
  push:
    paths:
      - .github/workflows/scanmsg.yml
      - data/text/*/*/*.msg
  pull_request:
    paths:
      - .github/workflows/scanmsg.yml
      - data/text/*/*/*.msg

jobs:
  ScanMsg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install wine
        uses: devopsx/gha-ubuntu-i386-fix@master

      - name: ScanMsg
        run: wine ./extra/bin/ScanMsg.exe data/text
